name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: nolabelregistry/devops:latest

  update-helm-chart:
    needs: build-and-push-docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update Helm chart
        run: |
          sed -i 's|image: .*|image: nolabelregistry/devops:latest|' ./helm/values.yaml
          cat ./helm/values.yaml

      - name: Package Helm chart
        run: helm package ./helm

      - name: Upload Helm chart
        uses: actions/upload-artifact@v2
        with:
          name: init-chart
          path: init-chart-*.tgz

  deploy-to-server:
    needs: update-helm-chart
    runs-on: ubuntu-latest
    steps:
      - name: Download Helm chart
        uses: actions/download-artifact@v2
        with:
          name: mychart

      - name: Copy Helm chart to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "mychart-*.tgz"
          target: "/tmp"

      - name: Deploy Helm chart
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            helm upgrade --install myrelease /tmp/mychart-*.tgz
